name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
      working-directory: ./shell
    - name: make chmod
      run: chmod +x make_tests.sh
      working-directory: ./shell
    - name: make tests
      run: ./make_tests.sh
      working-directory: ./shell
    - name: make chmod2
      run: chmod +x tests.sh
      working-directory: ./shell
    - name: tests
      run: ./tests.sh
      working-directory: ./shell
